### ISSUE TITLE
Error when clicking on "Instance details"

### ISSUE THREAD

**Issue by SergioRius** [TotallyInformation/node-red-contrib-uibuilder#121]
### Software and Package Versions

Software       | Version
-------------- | -------
Node.JS        | 12.20.1
npm            | 6.14.10
Node-RED       | 1.2.9
uibuilder node | 3.2.0
OS             | Debian 10 + Docker.
Browser        | Chrome

### How is Node-RED installed? Where is uibuilder installed?

Standard docker install

### Error shown:
```
TypeError: Cannot read property 'constructor' of undefined
    at /data/node_modules/node-red-contrib-uibuilder/nodes/uiblib.js:1144:39
    at Array.forEach (<anonymous>)
    at Object.showInstanceDetails (/data/node_modules/node-red-contrib-uibuilder/nodes/uiblib.js:1142:25)
    at /data/node_modules/node-red-contrib-uibuilder/nodes/uibuilder.js:745:31
    at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/node-red/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/node-red/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/node-red/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/src/node-red/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/node-red/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/usr/src/node-red/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/node-red/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/node-red/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/node-red/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/node-red/node_modules/express/lib/router/index.js:275:10)
    at query (/usr/src/node-red/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/node-red/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/node-red/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/node-red/node_modules/express/lib/router/index.js:335:12)
```

**Comment by TotallyInformation** [comment]
Will release 3.2.1 shortly - hopefully in the next 2-3 hours.
