### ISSUE TITLE
Uncaught TypeError: l.checkValidity is not a function

### ISSUE THREAD

**Issue by frclaude** [TotallyInformation/node-red-contrib-uibuilder#207]
Software       | Version
-------------- | -------
Node.JS        | v18.15.0
npm            | 9.6.3
Node-RED       | 3.0.2
uibuilder node | 6.3.0
uibuilderFE    | 6.3.0-iife.min
OS             | debian 10
Browser        | Edge on Windows 10

### How is Node-RED installed? Where is uibuilder installed?
From Node-Red palette.

So i followed your documentation about Svelte : [Using with uibuilder] and [Going further].
The template page displays well, changes saved in App.svelte are immediatly reported on the front-end.
The Edge Devtools->Network shows 3 files : /uibuilder/uibuilder.iife.min.js, /Sveltetest2/build/bundle.js, /livereload.js?snipver=1

There is 2 buttons on the example page : 

- The one using the sendToNR function works well.
- But the one using `button on:click={uibsend} data-greeting="{myGreeting}"  data-type="eventSend" data-foo="Bah" type="button"
					title="Uses the uibuilder.eventSend fn and sents both static and dynamic data back to Node-RED">` makes the following error in the console : 
`uibuilder.module.js:2187 
        
       Uncaught TypeError: l.checkValidity is not a function
    at uibuilder.module.js:2187:40
    at Array.forEach (<anonymous>)
    at y.eventSend (uibuilder.module.js:2168:40)
    at HTMLButtonElement.<anonymous> (App.svelte:25:29)`.

Can you tell me what I did wrong ?
Thanks for your attention, and for your work that I am looking forward to use.

**Comment by TotallyInformation** [comment]
OK, I've managed to reproduce that. I'm just not sure how! Looks like when I added a logLevel change line to my App.svelte and it rebuilt, that's when the error appeared. So I must have made a change to the uibuilder library that it doesn't like.

Adding a log output to the uibuilder library, I can now see that the HTML form gains an extra entry:

![image](https://user-images.githubusercontent.com/1591850/230153577-22698f61-fe20-415a-ba69-886ca0e5ec1a.png)

Sneaky old Svelte!

So I need to add a work-around and publish a bug-fix of the library.

**Comment by TotallyInformation** [comment]
Fixed in release 6.3.1 - about to be published.

**Comment by frclaude** [comment]
The bug has disapeared in v6.3.1, thank you a lot !!!
