### ISSUE TITLE
Building app into dist folder using webpack

### ISSUE THREAD

**Issue by Agarka** [TotallyInformation/node-red-contrib-uibuilder#42]
when i run webpack - following error on terminal : 

kajala@kajala-ThinkPad-T480s:~/.node-red$ webpack
/home/kajala/.node-red/node_modules/webpack-cli/bin/cli.js:235
				throw err;
				^

Error: Cannot find module 'html-webpack-plugin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (/home/kajala/.node-red/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/kajala/.node-red/webpack.config.js:3:27)
    at Module._compile (/home/kajala/.node-red/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (/home/kajala/.node-red/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/home/kajala/.node-red/node_modules/webpack-cli/bin/convert-argv.js:115:13)
    at requireConfig (/home/kajala/.node-red/node_modules/webpack-cli/bin/convert-argv.js:117:6)
    at /home/kajala/.node-red/node_modules/webpack-cli/bin/convert-argv.js:124:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/kajala/.node-red/node_modules/webpack-cli/bin/convert-argv.js:122:15)
    at yargs.parse (/home/kajala/.node-red/node_modules/webpack-cli/bin/cli.js:232:39)
    at Object.parse (/home/kajala/.node-red/node_modules/yargs/yargs.js:567:18)
    at /home/kajala/.node-red/node_modules/webpack-cli/bin/cli.js:210:8
    at Object.<anonymous> (/home/kajala/.node-red/node_modules/webpack-cli/bin/cli.js:500:3)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at module.exports.filename (/usr/local/lib/node_modules/webpack-cli/node_modules/import-local/index.js:16:66)
    at /usr/local/lib/node_modules/webpack-cli/bin/cli.js:13:6

**Comment by Agarka** [comment]
Now the error becomes : (after i executed npm link webpack)

Hash: de2e2b160b67184fdfda
Version: webpack 4.29.0
Time: 647ms
Built at: 01/23/2019 5:03:58 PM
 1 asset
Entrypoint main = bundle.min.js
[15] (webpack)/buildin/global.js 472 bytes {0} [built]
[27] multi ./uibuilder/vue/src/index.js normalize.css 40 bytes {0} [built]
[28] ./uibuilder/vue/src/index.js 4.77 KiB {0} [built]
[52] ws (ignored) 15 bytes {0} [optional] [built]
[55] ./uibuilder/vue/src/index.css 1.08 KiB {0} [built]
[56] ./node_modules/css-loader/dist/cjs.js!./uibuilder/vue/src/index.css 1.38 KiB {0} [built]
    + 54 hidden modules

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

**ERROR in bundle.min.js from UglifyJs
Unexpected token: keyword (const) [bundle.min.js:6275,0]
Child html-webpack-plugin for "index.html":**
     1 asset
    Entrypoint undefined = index.html
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./uibuilder/vue/src/index_template.html 4.07 KiB {0} [built]
    [2] (webpack)/buildin/global.js 472 bytes {0} [built]
    [3] (webpack)/buildin/module.js 497 bytes {0} [built]
        + 1 hidden module

**Comment by TotallyInformation** [comment]
It looks like it is objecting to a `const` definition somewhere in one of the js assets. You will need to have a look at the `bundle.min.js` file for character 6275 to see what file that came from originally then we can start to work out what has caused it.

As long as Webpack is using a suitably current version of Uglify, there should be no problems with uibuilder. Indeed, I use Uglify to create the `uibuilderfe.min.js` version. UglifyJS v3.4.9 is what I'm using at the moment. There were some older versions of Uglify that couldn't cope with some ES6 features.

**Comment by TotallyInformation** [comment]
Hi again, I have now done some testing with webpack and I can say with some confidence that it works just fine. I've tested with webpack v4.29.0 and the instructions for getting things working are linked below.

Please try these instructions - you may need to trim back your code to the bare minimum in order to prove that it isn't uibuilderfe that is causing the issue but rather something else.

https://github.com/TotallyInformation/node-red-contrib-uibuilder/wiki/Using-VueJS-with-Webpack
