### ISSUE TITLE
When a uibuilder node gets deleted, uibindex will give a TypeError.

### ISSUE THREAD

**Issue by boisei0** [TotallyInformation/node-red-contrib-uibuilder#59]
### Software and Package Versions
Software       | Version
-------------- | -------
Node.JS        | v10.16.2
npm            | v6.9.0
Node-RED       | v0.20.7
uibuilder node | v2.0.0
uibuilderFE    | v2.0.0 (I believe as I can't currently access uibindex)
OS             | Mac OS Mojave 10.14.5 (Darwin 18.6.0 x64 LE)
Browser        | Firefox 68.0.1

### How is Node-RED installed? Where is uibuilder installed?
userDir is `~/.node-red`, node-red installed through `npm install -g node-red`, uibuilder through palette upgrading existing latest v1 to v2.

### Issue:
When adding a uibuilder node to the flow, it gets added to `uib.instances`. [When this node is then deleted, it is set to `undefined`.](https://github.com/TotallyInformation/node-red-contrib-uibuilder/blob/fa22eb4a78c6ec46ff68a79e3ef45aa6876803c8/nodes/uiblib.js#L126) This does however cause a problem with `uibindex`. Deleting a node, deploying the changes, then accessing `/uibindex` gives the following error:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:1147:7)
    at Object.keys.forEach.key (/Users/afelix/.node-red/node_modules/node-red-contrib-uibuilder/nodes/uibuilder.js:1258:45)
    at Array.forEach (<anonymous>)
    at /Users/afelix/.node-red/node_modules/node-red-contrib-uibuilder/nodes/uibuilder.js:1254:44
    at Layer.handle [as handle_request] (/Users/afelix/.nvm/versions/node/v10.16.2/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/afelix/.nvm/versions/node/v10.16.2/lib/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
    at /Users/afelix/.nvm/versions/node/v10.16.2/lib/node_modules/node-red/node_modules/@node-red/editor-api/lib/auth/index.js:74:13
    at Layer.handle [as handle_request] (/Users/afelix/.nvm/versions/node/v10.16.2/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/afelix/.nvm/versions/node/v10.16.2/lib/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
```

As [line 1258 of `uibuilder.js`](https://github.com/TotallyInformation/node-red-contrib-uibuilder/blob/fa22eb4a78c6ec46ff68a79e3ef45aa6876803c8/nodes/uibuilder.js#L1258) shows, it accesses the `uib.instances` with the key found while looping through `uib.instances`. As mentioned above, when a node is deleted the value is set to undefined. 
This will cause `path.join()` to fail, as it can't handle arguments that are not strings. Adding a check [to the start of the forEach](https://github.com/TotallyInformation/node-red-contrib-uibuilder/blob/fa22eb4a78c6ec46ff68a79e3ef45aa6876803c8/nodes/uibuilder.js#L1255) to skip when `uib.instances[key]` is undefined should solve this.

**Comment by TotallyInformation** [comment]
Fixed in v2.0.1 about to be published. Many thanks Lena.
